import type { Metadata } from 'next';
import Sidebar from '@/components/Dashboard/Sidebar';
import FooterColorSetter from '@/components/Footer/FooterColorSetter';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="flex mt-12">
        <Sidebar />
        {children}
      </div>
      <FooterColorSetter color="bg-[#F3F4F6]" />
    </>
  );
}
